"""Orchestration: chunk -> prompt -> watsonx.ai -> assembled output file.

Main entry point for the pipeline agent is :func:`transform_program`.

Mock mode:
    Set MOCK=1 in the environment. All model calls are replaced with
    deterministic stub translations that are clearly marked as mock output.
    No WatsonxClient is created and no network call is ever attempted,
    so the full pipeline is testable with zero credentials.
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone

from .chunking import Chunk, chunk_ir
from .prompts import JAVA, PYTHON, TARGETS, build_prompt
from .watsonx import WatsonxClient, WatsonxError

MOCK_ENV_VAR = "MOCK"
MOCK_BANNER_JAVA = "// === MOCK TRANSLATION (MOCK=1): stub output, NOT from a real model ==="
MOCK_BANNER_PYTHON = "# === MOCK TRANSLATION (MOCK=1): stub output, NOT from a real model ==="


def is_mock_mode() -> bool:
    """True when the MOCK=1 environment variable is set."""
    return os.environ.get(MOCK_ENV_VAR, "").strip() == "1"


def transform_program(
    ir: dict,
    target: str = JAVA,
    client: WatsonxClient | None = None,
) -> str:
    """Translate a whole parsed COBOL program to *target* source code.

    Args:
        ir:     parsed program dict following the IR schema.
        target: "java" or "python".
        client: optional WatsonxClient. In real mode one is created from
                the environment when omitted; in mock mode it is ignored
                (and never created).

    Returns:
        The complete translated source file as a string, including a
        provenance header.
    """
    target = target.lower()
    if target not in TARGETS:
        raise ValueError(f"Unsupported target {target!r}; expected one of {TARGETS}")

    chunks = chunk_ir(ir)
    if is_mock_mode():
        translated = [_mock_translate(chunk, target) for chunk in chunks]
        provenance = _provenance_header(ir, target, model="MOCK (MOCK=1)")
    else:
        client = client or WatsonxClient()  # raises MissingCredentialsError
        translated = [
            _real_translate(chunk, target, client) for chunk in chunks
        ]
        provenance = _provenance_header(
            ir, target, model=client.config.model_id
        )

    body = "\n\n".join(translated)
    return f"{provenance}\n\n{body}\n"


def translate_chunk(
    chunk: Chunk,
    target: str = JAVA,
    client: WatsonxClient | None = None,
) -> str:
    """Translate a single Chunk to *target* source code.

    Uses the mock stub when MOCK=1, otherwise calls watsonx.ai.

    Returns:
        Translated code for the paragraph (without the file header).
    """
    target = target.lower()
    if target not in TARGETS:
        raise ValueError(f"Unsupported target {target!r}; expected one of {TARGETS}")
    if is_mock_mode():
        return _mock_translate(chunk, target)
    client = client or WatsonxClient()
    return _real_translate(chunk, target, client)


def write_output(text: str, path: str) -> str:
    """Write translated source *text* to *path*; returns *path*."""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return path


# ----------------------------------------------------------------------
# real path
# ----------------------------------------------------------------------
def _real_translate(chunk: Chunk, target: str, client: WatsonxClient) -> str:
    prompt = build_prompt(chunk, target)
    fence = "java" if target == JAVA else "python"
    try:
        raw = client.generate(
            prompt,
            max_new_tokens=2000,
            temperature=0.0,
            stop_sequences=["```\n\n", "COBOL paragraph"],
        )
    except WatsonxError as exc:
        raise WatsonxError(
            f"translation failed for paragraph {chunk.paragraph_name!r}: {exc}"
        ) from exc
    return _extract_code_block(raw, fence) or raw.strip()


def _extract_code_block(text: str, fence: str) -> str:
    """Pull the ```<fence> ... ``` block out of model output, if present."""
    match = re.search(
        rf"```{fence}\s*\n(.*?)```", text, re.DOTALL | re.IGNORECASE
    )
    if match:
        return match.group(1).strip()
    # fall back to any fenced block
    match = re.search(r"```\s*\n(.*?)```", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return ""


def _provenance_header(ir: dict, target: str, model: str) -> str:
    program = ir.get("program", "<unnamed>") if isinstance(ir, dict) else "<unnamed>"
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    if target == JAVA:
        comment = "//"
    else:
        comment = "#"
    return "\n".join(
        [
            f"{comment} Generated by retro-transformer (transformation engine)",
            f"{comment} Source COBOL program: {program}",
            f"{comment} Target language: {target}",
            f"{comment} Model: {model}",
            f"{comment} Generated at: {stamp} UTC",
        ]
    )


# ----------------------------------------------------------------------
# mock path -- deterministic stubs, clearly marked, zero network
# ----------------------------------------------------------------------
def _mock_translate(chunk: Chunk, target: str) -> str:
    if target == JAVA:
        return _mock_java(chunk)
    return _mock_python(chunk)


def _mock_java(chunk: Chunk) -> str:
    method = _to_camel(chunk.paragraph_name)
    lines = [MOCK_BANNER_JAVA, f"// paragraph: {chunk.paragraph_name}"]
    lines.append(f"public static void {method}() {{")
    for stmt in chunk.statements:
        text = str(stmt.get("text", "")).strip()
        line = stmt.get("line", "?")
        lines.append(f"    // COBOL [{stmt.get('type', '?')}] line {line}: {text}")
        lines.append('    System.out.println("MOCK");')
    lines.append("}")
    return "\n".join(lines)


def _mock_python(chunk: Chunk) -> str:
    func = _to_snake(chunk.paragraph_name)
    lines = [MOCK_BANNER_PYTHON, f"# paragraph: {chunk.paragraph_name}"]
    lines.append(f"def {func}():")
    if not chunk.statements:
        lines.append("    pass")
    for stmt in chunk.statements:
        text = str(stmt.get("text", "")).strip()
        line = stmt.get("line", "?")
        lines.append(f"    # COBOL [{stmt.get('type', '?')}] line {line}: {text}")
        lines.append('    print("MOCK")')
    return "\n".join(lines)


def _to_snake(name: str) -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z]+", "_", name.strip()).strip("_").lower()
    return cleaned or "paragraph"


def _to_camel(name: str) -> str:
    parts = [p for p in re.split(r"[^0-9a-zA-Z]+", name.strip()) if p]
    if not parts:
        return "paragraph"
    first = parts[0].lower()
    rest = "".join(p[:1].upper() + p[1:].lower() for p in parts[1:])
    camel = first + rest
    if camel and camel[0].isdigit():
        camel = "p_" + camel
    return camel
